config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :restaurants do
    resources :menu_items
    resources :orders
  end

  post '/restaurant/:id/new_menu_item' => 'restaurants#new.menu'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
	belongs_to :restaurant
	
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :restaurant

  def sum
  	@total = 0

  	orders.each do |o|
  		@total = @total + o.cost
  	end

  	puts @total
  end
  
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :menu_items, dependent: :destroy
	has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
	def create
     @restaurant = Restaurant.find(params[:restaurant_id])
     @menu_item = @restaurant.menu_items.create(menu_item_params)
     redirect_to restaurant_path(@restaurant)
    end

    def destroy
	  @restaurant = Restaurant.find(params[:restaurant_id])
	  @menu_item = @restaurant.menu_items.find(params[:id])
	  @menu_item.destroy
	  redirect_to restaurant_path(@restaurant)
	end

  private
    def menu_item_params
      params.require(:menu_item).permit(:item, :cost)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
   @restaurant = Restaurant.find(params[:restaurant_id])
   @order = @restaurant.orders.create(order_params)
   redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @order = @restaurant.orders.find(params[:id])
    @order.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private
    def order_params
      params.require(:order).permit(:name, :item, :cost)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @menu_items = MenuItem.all
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurants_path, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :website, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Item</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.item %></td>
        <td><%= order.cost %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Item:</strong>
  <%= @order.item %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @order.cost %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Website</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.website %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.id  %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/new.menu.html.erb
<h1>New Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="restView">
  <span class="restInfo">
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </span>
  
  <span class="restInfo">
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </span>
  
  <span class="restInfo">
    <strong>Website:</strong>
    <a href="http://<%= @restaurant.website %>" target="_blank" rel="nofollow"><%= @restaurant.website %></a>
  </span>
  <span class="restInfo">  
    <strong>Phone:</strong>
    <%= @restaurant.phone %>
  </span> 
  <div>
    <%= link_to 'Edit Restaurant Info', edit_restaurant_path(@restaurant) %> | 
    <%= link_to 'Back to Restaurants', restaurants_path %>
  </div>

</div>

<hr>

<div class="forms">
  <div class="col-sm-6">
    <h2>Menu Items</h2>
    <div class="menuList">
      <% @restaurant.menu_items.each do |menu_item| %>
      <div class="menuItem">
        <strong>Item:</strong>
        <%= menu_item.item %>

        <strong>Cost:</strong>
        $<%= menu_item.cost %>

        <%= link_to 'Remove', [menu_item.restaurant, menu_item],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>
    </div>
    <br>
    <hr class="dividerLine">
    
    <h4>Add a menu item:</h4>
    <%= form_for([@restaurant, @restaurant.menu_items.build]) do |f| %>
    
    <p>
      <%= f.label :item %>
      <%= f.text_field :item %>
    </p>
    <p>
      <%= f.label :cost %>
      <%= f.text_field :cost %>
    </p>
    <p>
      <%= f.submit "Add Item" %>
    </p>
    <% end %>

  </div>

  <div class="col-sm-6">
    <h2>Orders</h2>
    <div class="orderList">
      <% @restaurant.orders.each do |order| %>
      <div class="orderItem">
        <%= check_box_tag 'order_ids[]',  order.id, false %>
        <strong>Name:</strong>
        <%= order.name %>

        <strong>Item:</strong>
        <%= order.item %>

        <strong>Cost:</strong>
        $<%= order.cost %>

        <%= link_to 'Remove', [order.restaurant, order],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>
    </div>
    <br>
    <h5>Total: <%= @restaurant.orders.sum(:cost) %></h5>
    <hr class="dividerLine">
    <h4>Add an order item:</h4>
    <%= form_for([@restaurant, @restaurant.orders.build]) do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :item %>
      <%= f.text_field :item %>
    </p>
    <p>
      <%= f.label :cost %>
      <%= f.text_field :cost %>
    </p>
    <p>
      <%= f.submit "Add Order" %>
    </p>
    <% end %>

  </div>

</div>